config/routes.rb
Rails.application.routes.draw do
  resources :buddyships
  devise_for :users

  resources :users do
    collection do
      get "search_result"
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddyship.rb
class Buddyship < ApplicationRecord
	belongs_to :user
	belongs_to :buddy, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def after_sign_in_path_for(resource)
      user_path(resource) || stored_location_for(resource) || root_path
    end
    
	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  end
end

app/controllers/buddyships_controller.rb
class BuddyshipsController < ApplicationController

  # POST /buddyships
  # POST /buddyships.json
  def create
    @buddyship = current_user.buddyships.build(buddy_id: params[:buddy_id])
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = current_user.id
    current_user.current_buddy = user.id
    user.status = "Buddied-Up"
    current_user.status = "Buddied-Up"
    user.save
    current_user.save

    respond_to do |format|
      if @buddyship.save
        format.html { redirect_to current_user.buddies.last, notice: 'Buddied' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { redirect_to current_user, error: 'Could not buddy-up' }
        format.json { render json: @buddyship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddyships/1
  # DELETE /buddyships/1.json
  def destroy
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = nil
    current_user.current_buddy = nil
    if current_user.buddies.blank?
      current_user.status = "Buddy-less"
    end
    user.save
    current_user.save

    @buddyship = current_user.buddyships.where("buddy_id = ? and user_id = ?", params[:buddy_id], current_user.id).first
    @buddyship.destroy
    respond_to do |format|
      format.html { redirect_to user, notice: 'De-Buddified' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def buddyship_params
      params.require(:buddyship).permit(:user_id, :buddy_id, :create, :destroy)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_buddy = User.find_by_id(@user.current_buddy)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_result
    @users = User.search params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id params[:id]
    return redirect_to :root, flash: { error: "User not found" } if @user.blank?
    end

    def validate_user
      return redirect_to :root, flash: { error: "You are not allowed to access this page" } unless @user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :major, :education_level, :current_buddy, :status, :course_code, :goal, :picture, {skill: [], course_name: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(name)
    {
      "notice"  => "alert alert-info",
      "success" => "alert alert-success",
      "error"   => "alert alert-danger",
      "alert"   => "alert alert-danger",
    }[name]
	 end

end

app/helpers/buddyships_helper.rb
module BuddyshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="loginpage-cont signupPage">
      <div class="loginpage-inner">
        <h3>Let your future buddies know about yourself!</h3>
        <%= form_for(user) do |f| %>

          <% if user.errors.any? %>
            <div class="alert alert-error alert-block">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <ul>
                <% user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="sign-form form-horizontal span10 wrapper-center">

            <%= image_tag user.picture.url(:thumb), class: "edit-picture-style" %>
            <%= f.file_field :picture %>

            <div class='control-group'>
              <%= f.label :name, 'Name:', class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_field :name, class: "text-fields", maxlength: 50, required: true %>
              </div>
            </div>

            <div class="field">
              <%= f.label :status, "Buddy-Status:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.select :status, User::STATUS, {include_blank: "Select your Buddy-Status"},class: 'text-fields drop-down-select', required: true %>
              </div>
            </div>

             <div class="control-group paddingForAlerts">
              <%= f.label :phone, "Phone:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_field :phone, placeholder: "(xxx)-xxx-xxxx", maxlength: 16, class: 'text-fields' %>
              </div>
            </div>

            <div class="control-group paddingForAlerts">
                <%= f.label :major, "Major:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.select :major, User::MAJORS, {include_blank: 'Select your Major'}, class: 'text-fields drop-down-select' %>
              </div>
            </div>

            <div class="control-group paddingForAlerts">
              <%= f.label :education_level, "Education Level:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.select :education_level, User::EDUCATION_LEVELS, {include_blank: "Select your education level"}, class: 'text-fields drop-down-select' %>
              </div>
            </div>

            <div class="control-group paddingForAlerts">
              <%= f.label :current_buddy, "Current Buddy:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_field :current_buddy, class: 'text-fields' %>
              </div>
            </div>

            <div class="field">
              <%= f.label :skill, "Skills you can Teach:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_field :skill, name: "user[skill][]", class: 'text-fields' %>
              </div>
            </div>

            <div class="field">
              <%= f.label :course_name, "Courses You have taken:", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_field :course_name, name: "user[course_name][]", class: 'text-fields' %>
              </div>
            </div>

            <div class="field">
              <%= f.label :goal, "What do you aspire to do?", class: 'control-label .col-md-4', style: "margin-top: 10px;" %>
              <div class="controls .col-md-8">
                <%= f.text_area :goal, class: 'text-fields', style: "min-height: 200px; resize: vertical;" %>
              </div>
            </div>

            <div class='actions'>
              <%= f.submit 'Update', class: 'btn btn-outline btn-secondary pull-right' %>
            </div>
        <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div style="margin-left: 58px;">
	<%= link_to 'Go to your Profile', @user, class: 'btn btn-outline btn-secondary pull-left', style: "margin-top: 40px;" %>
</div>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div style="margin-top: 70px;" class="row-fluid">
  <div class="user-profile">
    <h3>Welcome to <p class="homepage-title">Tech|Buddy</p></h3>
    <p style="color:#16e6e9; font-style: italic;">Buddy-up to share your knowledge and learn from others!</p>
    <p>Here you can find students from your campus and connect with them if you like their skills and want to learn from them.</br>
    You can also connect to create your course group projects, study groups or your personal projects.</p>
  </div>
  <% if !user_signed_in? %>
    <div style="margin:50px auto; width: 50%;">
      <div class="pull-left" style="margin-right: 10px; width:40%">
        <p class="button-heading">Start learning and sharing today!</p>
        <div style="position: relative; width: 100%;"><%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-homepage btn-homepage' %></div>
      </div>
      <div class="pull-right", style="margin-left: 10px; width:40%">
        <p class="button-heading">Already a user?</p>
        <div style="position: relative; width: 100%;"><%= link_to 'Sign in',  "/users/sign_in", class: 'btn btn-outline-homepage btn-homepage' %></div>
      </div>  
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/search_result.html.erb
<% if @users.blank? %>
	<p>No results found</p>
<% else %>
	<div class="results">
		<% @users.each do |user| %>
			<%= link_to user do %>
		    <div style="margin: 20px;" class="result">
			    <%= image_tag user.picture.url(:thumb), class: "buddy-picture-style" %>
			    <i class="search-result-name"><%= user.name.titleize %></i>
		    </div>
		  <% end %>
	  <% end %>
	</div>
<% end %>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="loginpage-cont signupPage">
    <div class="row loginpage-inner">

      <div class="col-md-4">
        <%= image_tag @user.picture.url(:medium), class: "picture-style" %>
        <div style="margin-left: 43px;", class="login-btns">
          <% if @user == current_user %>
            <ul>
              <li>
                <%= link_to edit_user_path(@user) do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <%= "Profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path(@user) do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <%= "Account" %>
                <% end %>
              </li>
            </ul>
          <% end %>
          <% if @user != current_user %>
            <% if !current_user.buddies.include?(@user) %>
              <%= link_to 'Buddy-Up', buddyships_path(buddy_id: @user), method: :post, class: 'btn btn-outline btn-secondary', style: "margin-left: 54px;" %>
            <% else %>
              <%= link_to 'De-Buddify', {controller: "buddyships", action: :destroy, buddy_id: @user.id}, method: :delete, class: 'btn btn-outline btn-secondary', style: "margin-left: 54px;" %>
            <% end %>
          <% end %>
          <div style="margin-top: 80px; color:#555">
            <ul style="display: inline">
              <h4> Buddies: </h4>
              <% if !@user.buddies.blank? %>
                <% for buddy in @user.buddies %>
                  <li style="display: inline; margin: 5px; padding: 0px;">
                    <%= link_to user_path(buddy) do %>
                      <%= image_tag buddy.picture.url(:thumb), class: "buddy-picture-style" %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
              <% if !@user.inverse_buddies.blank? %>
                <% for inverse_buddy in @user.inverse_buddies %>
                  <li style="display: inline; margin: 5px; padding: 0px;">
                    <%= link_to user_path(inverse_buddy) do %>
                      <%= image_tag inverse_buddy.picture.url(:thumb), class: "buddy-picture-style" %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
              <% if @user.buddies.blank? and @user.inverse_buddies.blank? %>
                <p>No buddies yet! :( </p>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-md-8 profile">
        <div>
          <% if @user != current_user %>
            <h2><strong>Welcome to <%= @user.name.titleize %>'s Profile</strong></h2>
          <% else %>
            <h2><strong><%= @user.name.titleize %>'s Profile</strong></h2>
          <% end %>
        </div>

        <div>
          <i><strong>Phone:</strong></i>
          <p><%= @user.phone %></p>
        </div>

        <div>
          <i><strong>Status:</strong></i>
          <p><%= @user.status %></p>
        </div>

        <div>
          <i><strong>Major:</strong></i>
          <p><%= @user.major %></p>
        </div>

        <div>
          <i><strong>Education Level:</strong></i>
          <p><%= @user.education_level %></p>
        </div>

        <div>
          <i><strong>Current Buddy:</strong></i>
          <p>
            <% if @current_buddy.present? %>
              <%= link_to @current_buddy.name, @current_buddy %>
            <% end %>
          </p>
        </div>

        <div>
          <i><strong>Skills:</strong></i>
          <p>
            <% @user.skill.each do |s| %>  
              <%= s %>
            <% end %>
          </p>
        </div>

        <div>
          <i><strong>Courses Taken:</strong></i>
          <p>
            <% @user.course_name.each do |course| %>  
              <%= course %>
            <% end %>
          </p>
        </div>

        <div>
          <i><strong>Goals:</strong></i>
          <p style="min-height: 200px;"><%= @user.goal %></p>
        </div>
      </div>
      
    </div>
  </div>
</div>