config/routes.rb
Rails.application.routes.draw do
  resources :buddyships
  devise_for :users

  resources :users do
    collection do
      get "search_result"
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddyship.rb
class Buddyship < ApplicationRecord
	belongs_to :user
	belongs_to :buddy, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def after_sign_in_path_for(resource)
      user_path(resource) || stored_location_for(resource) || root_path
    end
    
	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  end
end

app/controllers/buddyships_controller.rb
class BuddyshipsController < ApplicationController

  # POST /buddyships
  # POST /buddyships.json
  def create
    @buddyship = current_user.buddyships.build(buddy_id: params[:buddy_id])
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = current_user.id
    current_user.current_buddy = user.id
    user.status = "Buddied-Up"
    current_user.status = "Buddied-Up"
    user.save
    current_user.save

    respond_to do |format|
      if @buddyship.save
        format.html { redirect_to current_user.buddies.last, notice: 'Buddied' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { redirect_to current_user, error: 'Could not buddy-up' }
        format.json { render json: @buddyship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddyships/1
  # DELETE /buddyships/1.json
  def destroy
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = nil
    current_user.current_buddy = nil
    if current_user.buddies.blank?
      current_user.status = "Buddy-less"
    end
    user.save
    current_user.save

    @buddyship = current_user.buddyships.where("buddy_id = ? and user_id = ?", params[:buddy_id], current_user.id).first
    @buddyship.destroy
    respond_to do |format|
      format.html { redirect_to user, notice: 'De-Buddified' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def buddyship_params
      params.require(:buddyship).permit(:user_id, :buddy_id, :create, :destroy)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_buddy = User.find_by_id(@user.current_buddy)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_result
    @users = User.search params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id params[:id]
    return redirect_to :root, flash: { error: "User not found" } if @user.blank?
    end

    def validate_user
      return redirect_to :root, flash: { error: "You are not allowed to access this page" } unless @user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :major, :education_level, :current_buddy, :status, :course_code, :goal, :picture, {skill: [], course_name: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(name)
    {
      "notice"  => "alert alert-info",
      "success" => "alert alert-success",
      "error"   => "alert alert-danger",
      "alert"   => "alert alert-danger",
    }[name]
	 end

end

app/helpers/buddyships_helper.rb
module BuddyshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_flash_message.html.erb
<div class="container" style="position: relative;">
  <div class="preLoginAlerts">
    <% flash.each do |name, msg| %>
      <div class="<%= flash_class(name) %> fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        	<%= content_tag :div, msg.html_safe %>
      </div>
    <% end %>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer>

    <p>
      Don't ever feel alone when you have the drive to be the better version of yourself. </br>
      Let's Teach and Learn together.
    </p>

</footer>

app/views/shared/_header.html.erb
<header id="header" role="banner">
  <div class="header-background">
    <div class="container">
      <div class="pull-left logo-sec">
        <%= link_to "Tech|Buddy", :root, class: "header-title" %>
      </div>
      <div class="pull-right">
        <div class="login-btns">
          <ul>
            <% if user_signed_in? %>
              <li>
                <%= link_to current_user do %>
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <%= "#{current_user.name}'s Profile" %>
                <% end %>
              </li>
              <li class="signoutLink"><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-thumbs-o-down" aria-hidden="true"></i> Sign Out
                <% end %>
              </li>
            <% else %>
              <li>
                <a href="/users/sign_up">
                  <i class="fa fa-hand-peace-o" aria-hidden="true"></i> Sign Up!
                </a>
              </li>
              <li>
                <a href="/users/sign_in">
                  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Sign In!!
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="search-bar">
      <%= form_tag(search_result_users_path, method: "get", id: "search-form") do %>
        <div class="input-group" style="width: 100%; margin: 0px auto;">
         <%= text_field_tag :search, params[:search], placeholder: "Search Buddies", class: "search-input " %>

            <%= button_tag(class: "btn btn-outline btn-secondary input-group-addon", style: "    width:50px;height:49px;padding:0px;margin:0px", name: nil) do %>
              <i class='fa fa-search' aria-hidden='true'></i>
            <% end %>

        </div>
      <% end %>
    </div>
  <% end %>
</header>