config/routes.rb
Rails.application.routes.draw do
  resources :buddyships
  devise_for :users

  resources :users do
    collection do
      get "search_result"
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddyship.rb
class Buddyship < ApplicationRecord
	belongs_to :user
	belongs_to :buddy, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def after_sign_in_path_for(resource)
      user_path(resource) || stored_location_for(resource) || root_path
    end
    
	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	  end
end

app/controllers/buddyships_controller.rb
class BuddyshipsController < ApplicationController

  # POST /buddyships
  # POST /buddyships.json
  def create
    @buddyship = current_user.buddyships.build(buddy_id: params[:buddy_id])
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = current_user.id
    current_user.current_buddy = user.id
    user.status = "Buddied-Up"
    current_user.status = "Buddied-Up"
    user.save
    current_user.save

    respond_to do |format|
      if @buddyship.save
        format.html { redirect_to current_user.buddies.last, notice: 'Buddied' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { redirect_to current_user, error: 'Could not buddy-up' }
        format.json { render json: @buddyship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddyships/1
  # DELETE /buddyships/1.json
  def destroy
    user = User.find_by_id(params[:buddy_id])
    user.current_buddy = nil
    current_user.current_buddy = nil
    if current_user.buddies.blank?
      current_user.status = "Buddy-less"
    end
    user.save
    current_user.save

    @buddyship = current_user.buddyships.where("buddy_id = ? and user_id = ?", params[:buddy_id], current_user.id).first
    @buddyship.destroy
    respond_to do |format|
      format.html { redirect_to user, notice: 'De-Buddified' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def buddyship_params
      params.require(:buddyship).permit(:user_id, :buddy_id, :create, :destroy)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_buddy = User.find_by_id(@user.current_buddy)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_result
    @users = User.search params[:search]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id params[:id]
    return redirect_to :root, flash: { error: "User not found" } if @user.blank?
    end

    def validate_user
      return redirect_to :root, flash: { error: "You are not allowed to access this page" } unless @user == current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :major, :education_level, :current_buddy, :status, :course_code, :goal, :picture, {skill: [], course_name: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(name)
    {
      "notice"  => "alert alert-info",
      "success" => "alert alert-success",
      "error"   => "alert alert-danger",
      "alert"   => "alert alert-danger",
    }[name]
	 end

end

app/helpers/buddyships_helper.rb
module BuddyshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buddyships/_form.html.erb
<%= form_for(buddyship) do |f| %>
  <% if buddyship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buddyship.errors.count, "error") %> prohibited this buddyship from being saved:</h2>

      <ul>
      <% buddyship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :buddy_id %>
    <%= f.number_field :buddy_id %>
  </div>

  <div class="field">
    <%= f.label :create %>
    <%= f.text_field :create %>
  </div>

  <div class="field">
    <%= f.label :destroy %>
    <%= f.text_field :destroy %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buddyships/edit.html.erb
<h1>Editing Buddyship</h1>

<%= render 'form', buddyship: @buddyship %>

<%= link_to 'Show', @buddyship %> |
<%= link_to 'Back', buddyships_path %>

app/views/buddyships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buddyships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Buddy</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buddyships.each do |buddyship| %>
      <tr>
        <td><%= buddyship.user_id %></td>
        <td><%= buddyship.buddy_id %></td>
        <td><%= buddyship.create %></td>
        <td><%= buddyship.destroy %></td>
        <td><%= link_to 'Show', buddyship %></td>
        <td><%= link_to 'Edit', edit_buddyship_path(buddyship) %></td>
        <td><%= link_to 'Destroy', buddyship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buddyship', new_buddyship_path %>

app/views/buddyships/new.html.erb
<h1>New Buddyship</h1>

<%= render 'form', buddyship: @buddyship %>

<%= link_to 'Back', buddyships_path %>

app/views/buddyships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @buddyship.user_id %>
</p>

<p>
  <strong>Buddy:</strong>
  <%= @buddyship.buddy_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @buddyship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @buddyship.destroy %>
</p>

<%= link_to 'Edit', edit_buddyship_path(@buddyship) %> |
<%= link_to 'Back', buddyships_path %>